### ISSUE TITLE
doc error: generatedAnnotation option 

### ISSUE THREAD

**Issue by tmtron** [xtext/xtext-gradle-plugin#104]
There is an error in the docs: http://xtext.github.io/xtext-gradle-plugin/xtext-builder.html

          generatedAnnotation {
            enabled = true
            ..
          }

according to the [XtextGenerate.xtend source code](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/XtextGenerate.xtend#L94) it must be: 

          generatedAnnotation {
            active = true
            ..
          }

**Comment by cdietrich** [comment]
fixed
