### ISSUE TITLE
IdeaPluginPlugin: Bug in collecting jars for ideaSandbox

### ISSUE THREAD

**Issue by amityadav1** [xtext/xtext-gradle-plugin#105]
Bug:
While creating the ideaSandbox, the ideaPluginPlugin code is copying files from the jar task to ideaSandBox/lib directory. It is also taking the runtimeDependencies, filtering all the jars also found in ideaProvided configuration and copying the remaining jars to the lib directory.

`assembleSandbox => [
			libraries.from(jar)
			libraries.from(runtimeDependencies.filter [ candidate |
				!providedDependencies.exists[hasSameArtifactIdAs(candidate)]
			])
			metaInf.from("META-INF")
		]
`
The problem is in the 'hasSameArtifactIdAs' and 'getArtifactId' code.

`private def hasSameArtifactIdAs(File file1, File file2) {
		file1.artifactId == file2.artifactId
	}
`
`	
	private def getArtifactId(File file) {
		val matcher = ARTIFACT_ID.matcher(file.name)
		if (matcher.matches) matcher.group(1) else null
	}
`
The above code will consider util.jar and util-core-factory.jar as the same artifact ('util) resulting in one of these jar being excluded from getting copied to assembleSandbox (and  I believe in plugin distribution as well). This then shows up as 'NoClassDefFound' exception in the idea ide.

I do not have the full context of why the dependencies are getting filtered and what the right filter criterion should be. 

Thanks,

Amit

**Comment by amityadav1** [comment]
Seems like this bug was introduced by 
'filter ideaProvided dependencies without taking version into account'  change (commit c8f2458e5fda399bf14bb916a24003dcb32ef46).

I think this can be fixed by simply changing the ARTIFACT_PATTERN to -> "(.*?)(-[0-9].*)?\\.jar"

**Comment by cdietrich** [comment]
maybe similar issue to the one fixed in mwe with https://github.com/eclipse/mwe/commit/7b0eb84cb6a194997504921de8698126df0d980f

@amityadav1 pull requests are welcome

**Comment by cdietrich** [comment]
Fixed in 1.0.21
