### ISSUE TITLE
gradle support for language build

### ISSUE THREAD

**Issue by meltzow** [xtext/xtext-gradle-plugin#11]
If I understand correct, this is a gradle plugin for using the language. But is there any plans or examples to build the language (jar-files) with gradle? So its possible to use it in a subproject for example.

Thank you

**Comment by oehme** [comment]
The answer is: It depends =) If you just want to build the runtime part, then yes, that's just a simple Java project.

For the Eclipse UI part, there is currently no support for building that in Gradle. But as part of the Buildship project, this will gradually improve. I'll leave this issue open as a reminder.

**Comment by otrosien** [comment]
I'd be interested in the current state of affairs building eclipse plugins with buildship/gradle.. Is there any news?

**Comment by oehme** [comment]
There is no news unfortunately. Since this would be a big effort, there would have to be a sponsor backing such a plugin.

**Comment by oehme** [comment]
Closing as this is unlikely to be done any time soon. There are ways to build Eclipse plugins with Gradle, e.g. using [Goomph](https://github.com/diffplug/goomph). But we are not at a point where we could build a convenient "Xtext UI" buildsystem on top of that. If you are interested in this, think about contributing to Goomph. Especially around a more Gradle-idiomatic DSL and support for multiple target platforms.
