### ISSUE TITLE
[question] Unable to build idea plugin with xtext=2.13.0, plugin=1.0.21

### ISSUE THREAD

**Issue by AmatanHead** [xtext/xtext-gradle-plugin#112]
Hello!

I'm trying to build my first xtext project and I'm having some issues with it so i thought maybe someone here could help me. I'm running `java 8`, `xtext=2.13.0`, `org.xtext:xtext-gradle-plugin=1.0.21`, `org.xtext:xtext-idea-gradle-plugin=1.0.21`, `gradle=4.6`. The project is a simple hello world that was generated by eclipse IDE.

The first error that I've encountered is

```
Execution failed for task ':org.xtext.example.mydsl.idea:downloadIdeaPlugins'.
> java.io.FileNotFoundException: http://download.eclipse.org/modeling/tmf/xtext/idea/2.13.0/updatePlugins.xml
```

If I try to remove the `pluginRepositories` section from the `ideaDevelopment`, the error changes to

```
Execution failed for task ':org.xtext.example.mydsl.idea:downloadIdeaPlugins'.
> java.net.MalformedURLException
```

What am I doing wrong?

Project files can be found here: [org.xtext.example.mydsl.parent.zip](https://github.com/xtext/xtext-gradle-plugin/files/1866379/org.xtext.example.mydsl.parent.zip)

**Comment by cdietrich** [comment]
Xtext 2.13 idea plugin was not published since the plugin is discontinued.

You might be able to build it from it's sources but it's state is unknown

**Comment by AmatanHead** [comment]
okay =( I think docs and eclipse template for new projects should be updated. Anyway, thanks for quick response!

**Comment by cdietrich** [comment]
Please open a ticketat eclipse/xtext-core about the wizard
