### ISSUE TITLE
Consider increasing base xtend and java version

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#116]
@oehme we at itemis are thinking about  increasing base xtend (to at least 2.12) and java version (to 8)
what do you think?

**Comment by cdietrich** [comment]
cc @arnedeutsch

**Comment by oehme** [comment]
Is there any pain in supporting older versions?

**Comment by cdietrich** [comment]
we will see when we try to get it running with gradle 4.7

**Comment by ArneDeutsch** [comment]
There is pain. First pain point found: https://github.com/xtext/xtext-gradle-plugin/issues/108

**Comment by ArneDeutsch** [comment]
For me it would look ok to day that if one uses a dated Xtext he can use a dated gradle as well. And a more recent version of Xtext supports more recent gradle versions. Are there issues that I'm probably not aware of?

**Comment by oehme** [comment]
I don't like coupling versions like that. If there is serious pain in supporting old versions, then I'm fine with dropping them. But saying "If you use an old Xtext version, you're also doomed to use an old Gradle version" is not very user friendly.

Minor differences can often be fixed using Proxies. The question is really: How many people are on each version? If most have moved on, then dropping the old ones is fine.

**Comment by ArneDeutsch** [comment]
Ok, can see your point. I will try to stick with old versions for now and just try to get gradle 4.7 working.

**Comment by ArneDeutsch** [comment]
I have increased java version to 1.8 inside https://github.com/xtext/xtext-gradle-plugin/issues/107 . Apart from this I would propose to close this ticket without further actions.
