### ISSUE TITLE
NoClassDefFoundError for additional lib needed in Validator

### ISSUE THREAD

**Issue by wuendsch** [xtext/xtext-gradle-plugin#12]
Hi,
I need the org.eclipse.core.resources.ResourcesPlugin in my DslValidator for checking files existing on the filesystem. 
But I get an NoClassDefFoundError. 
I already use the 

`xtext 'org.eclipse.birt.runtime:org.eclipse.core.resources:3.9.1.v20140825-1431'`

in my build.gradle. But nothing changes. The exception is thrown. 
how can I fix it? Or where can I define more deps for xtext build? The documentation of this plugin is very small.

thx.

**Comment by oehme** [comment]
The way you added the dependency is correct, **but:**

You cannot use core.resources in a standalone application, even if you had it on the classpath. There is no Eclipse running, so no ResourcesPlugin available. The runtime module of your language should never have such a dependency.
