### ISSUE TITLE
JDT 3.14 => memory explodes

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#120]
from xtext core plugin
```
* What went wrong:
Execution failed for task ':org.eclipse.xtext:generateXtext'.
> GC overhead limit exceeded
```

**Comment by cdietrich** [comment]
can be reproduced locally with

```./gradlew clean build -PuseJenkinsSnapshots=true -x test -PcompileXtend=true```

**Comment by cdietrich** [comment]
=> needs to be analyzed on our and jdt side. potentially needs jdt bug

**Comment by cdietrich** [comment]
<img width="1426" alt="bildschirmfoto 2018-06-29 um 12 39 49" src="https://user-images.githubusercontent.com/238736/42088421-ac0d6456-7b99-11e8-80d4-60ded731e616.png">

**Comment by cdietrich** [comment]
@stephan-herrmann are you aware of any memory issues in jdt 3.14?

**Comment by cdietrich** [comment]
did some experiments based on my pr https://github.com/eclipse/xtext-extras/pull/264
i can see the performance degradation there too.

**Comment by stephan-herrmann** [comment]
> are you aware of any memory issues in jdt 3.14?

As compared to which previous version?

I wouldn't be too much surprised to see Java 9 support to require more resources. Other than that I have no idea.

Seeing batch.CompilationUnit up in your screenshot: is Xtext holding on to these? Do you perform some kind of clean-up after compilation? With the link to a ModuleBinding we indeed introduced a link into the internal binding graph (and possibly more). Given that all these are internal classes to be used only by the batch compiler we did not consider adding cleanup methods.

**Comment by cdietrich** [comment]
no the degradation is actuelly there between oxygen 3a and photon.
yes xtext is holding these in the resources.
i have the feeling the compilation units themselves no retain more stuff.

**Comment by cdietrich** [comment]
ill try to find out why we do it this wired way and if we can use any better api.

**Comment by stephan-herrmann** [comment]
Main diff in CompilationUnit R4_7_maintenance vs. HEAD: we _removed_ a reference to another comilation unit (for the module). To back your feeling: can you provide a similar profiler screenshot from a previous version?

**Comment by stephan-herrmann** [comment]
Of course using API is always better :)

**Comment by cdietrich** [comment]
yes but therefore i first need to understand what we do and why we do it and if there is a suitable api for that.

**Comment by cdietrich** [comment]
i will try to provide a screenshot but its hard to find the right moment in the "good" case

**Comment by cdietrich** [comment]
here is the screenshot for oxygen 3a. as you can see the java resource retain as good as nothing

<img width="1160" alt="bildschirmfoto 2018-06-30 um 22 42 50" src="https://user-images.githubusercontent.com/238736/42128956-4f80248e-7cb7-11e8-93b4-3ac70e5a67b0.png">

**Comment by cdietrich** [comment]
i think we
- should cache binary types and not name environment answers
- should clear the cache after load
- throw away the compilation unit after load or recreate it from the contents (if a recompile is needed)

**Comment by stephan-herrmann** [comment]
Hmm, the profiler screenshot for oxygen.3a is _too_ good. Since we don't see any top-level JDT objects it is obvious that JDT is not wasting memory. OTOH, once you hold on to CompilationUnits with a ModuleBinding reference large retained memory comes to no surprise. Is this really the same profiler view? \<shrug>

**Comment by cdietrich** [comment]
well the jdt stuff is even more down the list

<img width="1173" alt="bildschirmfoto 2018-07-01 um 00 04 29" src="https://user-images.githubusercontent.com/238736/42129336-63cb2d66-7cc2-11e8-9125-90fbafaa6bca.png">

**Comment by cdietrich** [comment]
<img width="1176" alt="bildschirmfoto 2018-07-01 um 00 07 13" src="https://user-images.githubusercontent.com/238736/42129350-c0147424-7cc2-11e8-93c4-fefc4122428e.png">

**Comment by cdietrich** [comment]
before
<img width="1180" alt="bildschirmfoto 2018-07-01 um 00 09 44" src="https://user-images.githubusercontent.com/238736/42129361-20c897c8-7cc3-11e8-8621-b34b843be7bc.png">
after
<img width="1162" alt="bildschirmfoto 2018-07-01 um 00 10 37" src="https://user-images.githubusercontent.com/238736/42129365-39df06de-7cc3-11e8-9ac0-613822b209e9.png">
=> many more gc root paths

**Comment by stephan-herrmann** [comment]
If you have a CompilationUnit without the ModuleBinding, perhaps the change is due to the fix for https://bugs.eclipse.org/520858 - previously the UnNamedModule was not stored in the CompilationUnit AFAICS. See [this commit](https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/diff/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/CompilationUnit.java?id=47c817431ea2ffe0f20a10b076970caf1e34b7ad)

**Comment by cdietrich** [comment]
seems they all come from the unnamed module is the compilation unit.
in the old version i never get to a state where more than 400mb is used.

**Comment by cdietrich** [comment]
> previously the UnNamedModule was not stored in the CompilationUnit 
yes that i can see as a difference

**Comment by cdietrich** [comment]
needs to be reexamined once we inc jdt version in Xtext

**Comment by cdietrich** [comment]
TODO: test this when we bump for Xtext 2.17

**Comment by cdietrich** [comment]
this is basically ok. there is a follow up task to investigate further https://github.com/eclipse/xtext-extras/issues/363
