### ISSUE TITLE
modelDirectory is handled in an unexpected manner

### ISSUE THREAD

**Issue by AresEkb** [xtext/xtext-gradle-plugin#123]
Hi

modelDirectory is handled in a very unexpected manner. You can try this example (can be build with either gradle 3.1, or xtext 2.10.0): https://github.com/ghillairet/xcore-gradle-example

1) If modelDirectory is specified in the model (https://github.com/ghillairet/xcore-gradle-example/blob/master/src/main/resources/model.xcore), then Java code is generated in build/xcore/main
An actual value of modelDirectory doesn't matter.

2) And if modelDirectory is unspecified, then Java code isn't generated at all.

I think that in the 2nd case the code must be generated at the default location. And in the 1st case it must be generated at the location specified in modelDirectory

**Comment by oehme** [comment]
The Xtext Gradle plugin knows nothing about Xcore. You need to specify your output directories in the plugin configuration like for any other Xtext language.

**Comment by AresEkb** [comment]
Thanks, I've got it.

But the strange thing is that Java code is not generated, when modelDirectory is unspecified. I'm not sure whether it's a problem in Xtext Gradle plugin, or not. But it's generated fine using Eclipse or Xtext Maven plugin. It seems that unspecified modelDirectory breaks something.

**Comment by oehme** [comment]
I don't know how Xcore decides what to do when no modelDirectory is given. Do you mean it's not generated even if you provide an output directory via the plugin configuration?

**Comment by cdietrich** [comment]
needs to be debugged but i assume some mappings for emf are not set correctly

**Comment by AresEkb** [comment]
Yep, I added output folder configuration in my fork: https://github.com/AresEkb/xcore-gradle-example

And with modelDirectory parameter present code is generated.

But if one will remove modelDirectory from https://github.com/AresEkb/xcore-gradle-example/blob/master/src/main/resources/model.xcore then Java code will not be generated.

**Comment by cdietrich** [comment]
org.eclipse.emf.ecore.xcore.generator.XcoreGenerator.generateGenModel(GenModel, IFileSystemAccess) tests for existence of modeldirectory. thus i am not sure if this is working in maven or eclipse

**Comment by cdietrich** [comment]
the change from model directoy to default output happens here: org.eclipse.emf.ecore.xcore.generator.XcoreGenModelGeneratorAdapterFactory.createOutputStream(URI)

=> seems intended too
