### ISSUE TITLE
Ease the usage of the plugin in a closed environment

### ISSUE THREAD

**Issue by mivola** [xtext/xtext-gradle-plugin#130]
As described in the forum (https://www.eclipse.org/forums/index.php?t=rview&goto=1796422) we're using the plugin in a closed environment. Therefore we're not able to reference any jars directly from jcenter() or mavenCentral() but only from a internal repository with a fixed naming convention.

Unfortunately there are two issues within the plugin itself that we're having problems with.

1)	The files in our repository follow a different naming schema and therefore the LIB_PATTERN does not match anything: https://github.com/xtext/xtext-gradle-plugin/blob/9a0a1dafc415aacc62c763cee9c8bf82f9e285f9/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/XtextExtension.xtend#L44
The plugin is expecting something like "org.eclipse.xtext-2.12.0.jar" but the jar in our repo is named "xtext-2.13.0-xtext2130.jar 
=> it would be nice if the plugin was "a bit smarter" to find XText libs or if we could specify the pattern within our gradle script

2)	We did work around 1) by specifying "xtext.version" but then the build fails b/c a hardcoded dependency to 'org.eclipse.xtend:org.eclipse.xtend.core:version' is added: https://github.com/xtext/xtext-gradle-plugin/blob/f4fb031452ef815c41dec85ee02760bec25e6b0b/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtendLanguageBasePlugin.xtend#L71
This dependency cannot be resolved in our repo b/c again the naming/GAV schema is different: the same jar can be found in our repo by "org.eclipse.xtend:xtend-lib" 
=> it would be nice if the plugin could determine if the dependency is already defined in our buildscript (by whatever name/GAV) or if we could specify the dependency name within our gradle script. We did work around this by using a local ivy repo and automatically copying the xtend-lib.jar into it (using the proper name/GAV). But that solution is not very easy to maintain and might break in the future.

So it would be good to make referencing those libraries a bit more flexible / customizable.

Thanks a lot!
Michael

**Comment by cdietrich** [comment]
as stated in the forum i am very sceptic on this. @oehme what do you think.
i am not familiar with the history why some of the "bad" places are inplace.

**Comment by oehme** [comment]
You can set the `xtextClasspath` property of the `XtextGenerate` task directly, cirumventing any autodetection based in the compile classpath.

**Comment by SlaviGp** [comment]
Hi All,

I have prepared example project which reproduce the issue. Please take a look and give us more hints about that problem.
[cross-compiler.zip](https://github.com/xtext/xtext-gradle-plugin/files/2836428/cross-compiler.zip)

`------------------------------------------------------------
Gradle 4.4-rc-5
------------------------------------------------------------

Build time:   2017-11-30 15:21:37 UTC
Revision:     f4daa310b16df9abd4f37257bae8312b5293a251

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 7 6.1 amd64`

Run build with command line args: `gradlew clean generateXtext`
