### ISSUE TITLE
Fix Github Pages warning

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#136]
The page build completed successfully, but returned the following warning for the `gh-pages` branch:

You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by oehme** [comment]
Fixed by https://github.com/xtext/xtext-gradle-plugin/pull/137
