### ISSUE TITLE
Configure xtendOutputDir in gradle kotlin dsl

### ISSUE THREAD

**Issue by sgarfinkel** [xtext/xtext-gradle-plugin#140]
I can't seem to figure this one out.

Unless there's an alternative way, there seems to no way I can find to express:

```groovy
sourceSets {
  main {
    xtendOutputDir = 'xtend-gen'
  }
  test {
    xtendOutputDir = 'test/xtend-gen'
  }
}
```

**Comment by cdietrich** [comment]
Ain’t setXtendOutputDir callable on XtendSourceSet

**Comment by sgarfinkel** [comment]
Not sure I follow, but I was curious if this would work and it doesn't seem to be for me:

```kotlin
configure<XtendSourceSet> {
    setXtendOutputDir("src/main/xtend-gen")
}
```

**Comment by oehme** [comment]
This property is dynamically added to the sourceSet, which means in Kotlin you have to be a bit more explicit to get a handle of it:

```
sourceSet.withConvention(XtendSourceSet::class) {
  xtendOutputDir = ...
}
```

**Comment by sgarfinkel** [comment]
@oehme Does this set the location globally or on main/test basis.
