### ISSUE TITLE
Replace Closure with Action<T>

### ISSUE THREAD

**Issue by sgarfinkel** [xtext/xtext-gradle-plugin#141]
In the Gradle Kotlin DSL using Groovy Closures is very inconvenient, and requires you to inspect the code to determine the Closure's argument type.

The [current recommendation](https://docs.gradle.org/current/userguide/kotlin_dsl.html#groovy_closures_from_kotlin) is to use the strongly typed Action<T>. Currently the plugin uses Closure<?> almost exclusively requiring end users need to explore the underlying internal code to determine the argument type for use in the Kotlin DSL.

**Comment by sgarfinkel** [comment]
Yes. I will make a PR. Question though: Should the implementation with Action<T> overload the existing Closure<?> implementation so that current Kotlin DSL users who are using `closureOf` don't encounter regressions or should this be a breaking change that completely replaces Closure<?>.

Groovy buildscript users will encounter no issues with a straight replacement.

**Comment by oehme** [comment]
I think we should keep the Closure-taking methods around until we do another major version.
