### ISSUE TITLE
Task ':compileJava' is not up-to-date

### ISSUE THREAD

**Issue by AresEkb** [xtext/xtext-gradle-plugin#144]
It seems that the Xtext plugin breaks incremental building. Here is [a sample project](https://github.com/AresEkb/xcore-gradle-test). If you will build it with `--info` key you will see the following message:

```
Task ':compileJava' is not up-to-date because:
  Additional action for task ':compileJava': was implemented by the Java lambda 'org.xtext.gradle.XtextBuilderPlugin$$Lambda$60/1535104547'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
```

**Comment by oehme** [comment]
Indeed, we should make this an explicit class instead of a lambda.

**Comment by szarnekow** [comment]
Are there other things that should be refactored, to get this into a better shape?

**Comment by oehme** [comment]
Any other usages of `doFirst`/`doLast`, but I think that's the only one.

**Comment by szarnekow** [comment]
Is this constraint documented / explained somewhere?

**Comment by oehme** [comment]
It's in the user guide [here](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:how_does_it_work).

**Comment by szarnekow** [comment]
Perfect! Thank you!

**Comment by oehme** [comment]
This was fixed a long time ago: https://github.com/xtext/xtext-gradle-plugin/commit/59cba63c423e93e921a0e015b5783b5663328134
