### ISSUE TITLE
Load DSL Files from Classpath - not from a Source Directory

### ISSUE THREAD

**Issue by dmitry-v-vlasov** [xtext/xtext-gradle-plugin#158]
Hello,

I know that this is a not so standard way of thinking how the Xtext code generation
should work but...
Is there a way based on the Xtext Builder Gradle Plugin to load the language source files (models written in a DSL) not from a local source folder but from a Gradle dependency, from a JAR file?

Is it possible to add this feature to the plugin?
The class XtextResourceSet can be used together with the class loading...
It seems quite weird to launch a handwritten MWE2 workflow for each M2T Gradle subproject instead of using the 'org.xtext.builder' plugin or an own Gradle plugin.
When I used Maven with Xtext 2.9.1 I had to copy-paste and modify the class ContextClassLoaderAwareRuntimeResourceSetInitializer from the Sculptor framework,
write an own Reader and copy-paste the WorkflowLauncher in order to launch all this stuff with the maven-exec-plugin. So with Gradle I have to implement the same kind of... solution.

Of course I can download the DSL sources JAR and unpack it manually to a local directory.

**Comment by kuniss** [comment]
As JARs are zip files you may use the following approach.

1. Define a special configuration
```
configurations {
	xtextSources
}
```

2. Specify a source dependency for it
```
dependencies {
	xtextSources 'my-artifact-group:my-artifact:1.2.3:sources'  
}
```
3. Define a variable `xtextSourcesDir` containing a relative project path the Xtext sources will be copied to, e.g.
```
def xtextSourcesDir = "$buildDir/xtext-src"
```

4. Define a source set for it to get it visible to the Xtext compiler.
```
sourceSets {
   main.java.srcDir xtextSourcesDir
}
```

5. Define an unpackaging task which copies the *.xtext files only to the project dir defined in  `xtextSourcesDir`  
```
task unzipXtextSources(type:Copy) {
	from zipTree(configurations.xtextSources.singleFile)
	into xtextSourcesDir
        include '**/*.xtext'
}
```

6. Make the Xtext generation task depend on the unpackaging task above
```
generateXtext {
	dependsOn unzipXtextSources
}
```
I'm using a similar solution for copying in Java source from a source JAR. So it works for me that way. I just made renamings (look for typos!) and added the include clause to the unpackaging task.

If you use Eclipse, the following line may be valuable too:
```
tasks.eclipseClasspath.dependsOn unzipXtextSources
```
P.S. The Xtext gradle plugin I'm using in this project is
```
id 'org.xtext.xtend' version '1.0.21'
```
A little bit old, but should work with the 2 version too.

**Comment by oehme** [comment]
I think this is a special case that doesn't warrant a feature in the plugin, since doing it yourself is straightforward in Gradle, as @kuniss showed.
