### ISSUE TITLE
Add project directory to Resource Map

### ISSUE THREAD

**Issue by sgarfinkel** [xtext/xtext-gradle-plugin#165]
This was also requested, and fixed, in the Maven plugin https://github.com/eclipse/xtext-maven/issues/26

I don't know how you update the ResourceMap given the plugin uses DI and ISetup to configure the languages. Is there a way to do this without directly accessing the EcorePlugin? Documentation about this seems pretty light (to non-existent).

Is the only solution currently for users to create a sibling project that provide an implementation of ISetup that correctly updates the ResourceMap?

**Comment by cdietrich** [comment]
Here is the contribution done for the maven plugin
https://github.com/eclipse/xtext-maven/commit/f3ce72f240814770a14268e1c4073ccace5985d4

It directly accesses it

Thus I have no idea what your question targets

**Comment by sgarfinkel** [comment]
Yeah this is primarily about Xcore. I want to generate Ecore when I run the code generator.

**Comment by cdietrich** [comment]
hmmmm i dont know if it is a good idea do patch this here.
i also dont know when xcore uses which entries from the map and when not.
do you think the plugin is patchable in this respect?

**Comment by sgarfinkel** [comment]
Not directly, no. Because the Maven Plugin directly depends on the EMF/Ecore toolchain, you can actually call the `EcorePlugin` class directly. However, since the gradle plugins uses ServiceLoader to load ISetup instances (without knowing anything about the underlying libraries and classes used), I don't know of any way to patch the plugin to configure Ecore.

I was mainly wondering if anyone had managed to solve this problem by using the StandaloneSetup infrastructure.

**Comment by oehme** [comment]
Well, you could add a compileOnly dependency on Ecore, do a check whether it is actually on the classpath at runtime and then do the appropriate setup code in the plugin. 

Alternatively you could provide a small helper library (let's call it `ecore-gradle-integration`) that has an ISetup that does the necessary adjustments. You'd then put that into `xtextClasspath`. But then the question is how this setup would get access to the workspace settings. 

I'm not very up-to-date on Xtext on Ecore anymore, so I might be missing another option.

**Comment by sgarfinkel** [comment]
@oehme fortunately the plugin does register an IProjectConfig, which properly points to the running gradle project's root, so we can leverage that. I'm currently getting very spurious results. In my sample project, I've created a sibling project, let's call it "setup". It simply contains this class:

```kotlin
class PatchedXcoreStandaloneSetup: XcoreStandaloneSetup() {
}
```

Just using that as the configured setup (instead of XcoreStandaloneSetup directly), gives different results. The most apparent is that it stops dumping code in the expected location ("build/xcore/main" by default)--not sure if there are other hidden discrepencies too.

What exactly is the lifecycle of these setups with respect to the plugin? Does it just call `createInjectorAndDoEMFRegistration()` and then stop interacting directly with the setup?

**Comment by oehme** [comment]
Yep that's [all it does](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-builder/src/main/java/org/xtext/gradle/builder/XtextGradleBuilder.xtend#L57).

**Comment by sgarfinkel** [comment]
So then there must be some sort of bug or race condition in Xcore's setup. There's no reason why a pure subclass should result in anything different from using the parent directly.

I would like to keep this issue open, however, since if I am able to find a reasonable solution I think others would want to have this for reference. I'll close if I'm able to come up with something.

**Comment by oehme** [comment]
Closing this since it doesn't seem to be a problem in the plugin, but rather in Xcore. 

> is the ClassLoader of the actual build process shared with the plugin

Sorry for missing that question - No, everything runs in an isolated classloader. But your approach of subclassing the ISetup should work.
