### ISSUE TITLE
ERROR:org.eclipse.emf.mwe.utils.StandaloneSetup cannot be resolved to a type.

### ISSUE THREAD

**Issue by hanibhat** [xtext/xtext-gradle-plugin#166]
I get the following error when running `sudo gradle assemble` in my project:

> ERROR:org.eclipse.emf.mwe.utils.StandaloneSetup cannot be resolved to a type.

Here are the dependencies versions: 

> xtext: 2.15.0
> xtext-gradle-plugin: 1.0.18
> java: 8

**Comment by cdietrich** [comment]
Can you please provide a reproducible example

**Comment by hanibhat** [comment]
I'm trying to work on the [MD2 framework](https://github.com/wwu-pi/md2-framework), which is built with xtext. You can follow the steps on [this page](https://wwu-pi.github.io/md2-framework/40_handbook-dev/420_installation-dev.html) to reproduce the problem.

**Comment by cdietrich** [comment]
the project you are building seems to have a broken setup. it misses e.g.
```
	compile "org.eclipse.emf:org.eclipse.emf.mwe.utils:1.3.21.201705291010"
```

also the versions for gradle, xtext and this plugin are hopelessly outdated.
you might also lead to increase gradle memory with that old setup.

**Comment by hanibhat** [comment]
Would you say the only to properly build this project is to update all the dependencies?

**Comment by cdietrich** [comment]
yes
