### ISSUE TITLE
Handle Travis-CI.org shutdown.

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#176]
Looks like travis-ci.org will be gone by the end of the year
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=[UNIQID]

wonder if we should move to travis-ci.com (https://docs.travis-ci.com/user/migrate/open-source-repository-migration)
or github actions

@oehme looks like you are the only person with knowlegde on the tokens.
can you please have a look?

**Comment by oehme** [comment]
I'm in favor of Github actions. 

The build needs two environment variables:
- ORG_GRADLE_PROJECT_bintrayApiKey
- ORG_GRADLE_PROJECT_sonatypePassword

These secrets should be configured with the credentials of the `xtext-team` account, which I think @svenefftinge owns.

**Comment by cdietrich** [comment]
it looks like i can create secrects? i assume you cant @oehme ?

**Comment by oehme** [comment]
I can do so too, but I don't have the passwords :)

**Comment by svenefftinge** [comment]
I have added two secrets here: https://github.com/xtext/xtext-gradle-plugin/settings/secrets
Please let me know if I understood something wrong or you need something else (through mail or twitter as I don't check GH notifications).
