### ISSUE TITLE
Deal with bintray/jcenter sunset

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#183]
it looks like bintry/jcenter will be gone in the foreseeable future so that we need a replacement

@oehme do you have any ideas?

**Comment by slonopotamus** [comment]
What about Maven Central?

**Comment by cdietrich** [comment]
yes. should be doable via ossrh

**Comment by slonopotamus** [comment]
Another possibility is GitHub Packages. See https://github.com/grandcentrix/grandcentrix-kotlin-either/pull/9/files for example of easy transition. Though I personally think that publishing to Maven Central is better for Java ecosystem.

**Comment by oehme** [comment]
Maven Central for sure. We already sync there via Bintray, but now we'll have to change the build to publish to Maven Central directly. I'll set some time aside for that this month.

**Comment by oehme** [comment]
I've refreshed my memory on the code a bit now and I actually think we can completely avoid JCenter/MavenCentral by publishing the whole thing as a single artifact to Gradle's plugin portal. It'll require some changes to how the plugin works, but that's okay. It'll make the whole thing simpler.

@svenefftinge or @cdietrich can one of you create an Xtext-Team account at https://plugins.gradle.org/ and configure the credentials on this repository, so they'll be available on Github actions?

**Comment by cdietrich** [comment]
@oehme i've been told that that plugin portal just forwards to bintray. has this changed? https://github.com/node-gradle/gradle-node-plugin/pull/140#issuecomment-774209930

**Comment by oehme** [comment]
It does not, no. It only includes jcenter because that's where Gradle plugins used to be published before the plugin portal had its own storage.

**Comment by cdietrich** [comment]
@svenefftinge i assume you are still owner of the xtext github org. so it would be nice if you could take care

**Comment by svenefftinge** [comment]
> @svenefftinge i assume you are still owner of the xtext github org. so it would be nice if you could take care

You are also an owner of the Xtext org here at GitHub (mad @oehme one as well now). Not sure what you asked I should do, though.

**Comment by cdietrich** [comment]
@svenefftinge 
i cannot login with github sso at gradle.
i thoight this would be the best way to create the account at gradle

**Comment by szarnekow** [comment]
Hey @oehme , do I understand it correctly that there is no way to associate a Github organization with an account at https://plugins.gradle.org ? Is it strictly necessary to have a *user* account being created there with own credentials? How do other orgs share access to these sort of accounts / revoke access again if the person that has access to the credentials leaves the organisation?

**Comment by oehme** [comment]
There are no organisations at the plugin portal. We'll have to do it the same way we did for Bintray and Maven Central, where we shared the xtext-team account. So someone who has access to that account needs to register it at plugins.gradle.org and then add the credentials in this repository's secrets section.

**Comment by szarnekow** [comment]
There is no such thing as an Xtext-team account (as far as I can tell) and I'm reluctant to introduce a new one with a questionable policy to share credentials.
What are the alternatives? Move this repo to the Eclipse org and publish the plugin to maven central instead of plugins.gradle.org - basically using the existing mechanism as for other artefacts? Is that an option?

**Comment by oehme** [comment]
There definitely was such an account, it was what we used for Bintray : https://github.com/xtext/xtext-gradle-plugin/blob/master/build.gradle#L22

The plugin portal is the place to put plugins. JCenter just used to be the way to get them there. Now it has its own storage and upload mechanism.

**Comment by oehme** [comment]
@svenefftinge Can you please create the above-mentioned account? Otherwise I won't be able to publish new versions of this plugin.

**Comment by cdietrich** [comment]
@oehme @svenefftinge if i understood correctly then @szarnekow will care about account creation

**Comment by oehme** [comment]
I didn't get that from the above, was there some private discussion? It's been 2 weeks since the last message.

**Comment by szarnekow** [comment]
I'm still not happy with the idea to have a shared account with a shared password. Is it possible to store aliases or additional mail addresses on the plugins.gradle.org account?

**Comment by oehme** [comment]
No, it is not, but that didn't stop us on jcenter either.

**Comment by szarnekow** [comment]
Ok, I created a dummy account. Looks like aliases are not supported and neither is there an obvious way to delete an account again. Not a great experience.

**Comment by oehme** [comment]
Please do tell to the Gradle team. That being said, if companies like Netflix, Microsoft and JetBrains can deal with that, I'm sure we can :)

**Comment by szarnekow** [comment]
Well companies are own legal entities and usually have a centralised means to store credentials for these kind of portals.

**Comment by oehme** [comment]
You don't need to share the password widely (maybe just you and Sven), since most interactions happen through the API key, which we'll need a a secret in this repo. We'll also need to claim the plugins as ours via this form: https://plugins.gradle.org/docs/get-help. The automatic claiming only works for individual Github accounts as far as I can see

**Comment by cdietrich** [comment]
@szarnekow what is the state here?

**Comment by oehme** [comment]
All the plugins are claimed and the secrets are set in this repository. I'll have to make some changes to the build in order to make it publish to the portal. I'll do that next time we want to do a release.

**Comment by oehme** [comment]
[Version 2.0.9](https://plugins.gradle.org/plugin/org.xtext.builder/2.0.9) was successfully published to the Portal. Thanks everyone!
