### ISSUE TITLE
xtend.gradle.plugin no longer works with java 8

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#186]
the xtend gradle plugin does no longer work with java 8
https://ci.eclipse.org/xtext/job/xtext-lib/job/master/46/console

see also https://github.com/eclipse/xtext/issues/1976

https://github.com/xtext/xtext-gradle-plugin/blob/eee22854a3d14f07c29ea90ee7c6ed119c9e34fb/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtendLanguageBasePlugin.xtend

@oehme do you have any idea how i can configure the transitive dependencies to use a specific core.runtime and equinox common?

**Comment by oehme** [comment]
Nothing Gradle plugin specific here, the problem is with the transitive dependencies of EMF. Let's discuss on the other issue.
