### ISSUE TITLE
More than one `.tests` project not working

### ISSUE THREAD

**Issue by tjeske** [xtext/xtext-gradle-plugin#194]
I am trying to get ridd of Maven and switch to Gradle in my Xtext project. My Gradle project consists of two subprojects for testing - the regular `.tests` project and another test project with another focus and another set of dependencies. The tests of both test projects although use DSL snippets as input and use the same Xtext testing infrastructure. I have added a dependency from the second test project to the standard `.test` project to access the generated language files for testing but Gradle complains that he can't resolve some types.
The problem can be reproduced by creating an Xtext project via project wizard (Gradle project, Junit5 testing, plain source layout) and duplicating the `.tests` project, name it e.g. `org.xtext.example.mydsl.abc.tests` and delete the `src-gen` directory of this new sub project. The error message after `./gradlew build` is

```
> Task :org.xtext.example.mydsl.abc.tests:generateTestXtext FAILED
ERROR:The method or field MyDslInjectorProvider is undefined (file:../MyDslParsingTest.xtend line : 16 column : 13)

FAILURE: Build failed with an exception.
```

It seems to be that the `generateTestXtext` task completely ignores the dependencies to other sub projects.

**Comment by oehme** [comment]
Can you please attach a self-contained example?
