### ISSUE TITLE
Performance issues when generating Java code from Xtend

### ISSUE THREAD

**Issue by rokkerboci** [xtext/xtext-gradle-plugin#195]
The xtend generation is significantly slower using using the plugin then using the Eclipse plugin.

**Comment by cdietrich** [comment]
do you have a significant number of java files in the projects too?
can you provide a yourkit snapshot?

**Comment by kthoms** [comment]
Is the effective classpath larger? Could you exclude dependencies?

**Comment by rokkerboci** [comment]
Thank you for the quick reply. Yes, since then I realised that we have a huge amount of dependencies, and that is the reason for the slowdown. I will try to reduce it. I think this issue can be closed, I will reopen if this doesn't solve the problem
