### ISSUE TITLE
Issues with JCenter outage

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#209]
```
* What went wrong:
A problem occurred configuring root project 'xtext-lib'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.google.guava:guava:[10.0.1,14.0.1].
     Required by:
         project : > org.xtext:xtext-gradle-plugin:3.0.2 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.9.0
         project : > org.xtext:xtext-gradle-plugin:3.0.2 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.9.0
      > Failed to list versions for com.google.guava:guava.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/com/google/guava/guava/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/guava/guava/maven-metadata.xml'.
               > Read timed out
```
wonder if we should bump the minimal versions to get rid of the rrange dependency to guava (and leverage the xtext dev bom)
the workarounds on https://discuss.gradle.org/t/plugin-portal-dependency-resolution-failing-due-to-jcenter-usage/44131/7
dont see to work

@oehme any idea?

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-lib/blob/ddce1451b3050d9470941b79a8382d7604149a98/gradle/bootstrap-setup.gradle#L23 also seems to be (partially) useless as the problem seems to happen before

**Comment by cdietrich** [comment]
looks like the problem is starting to resolve on gradle plugin portal or jcenter side, but i wonder how to avoid jcenter alltogether

**Comment by cdietrich** [comment]
meanwhile the error message has changed to 

```
 A problem occurred configuring root project 'org.xtext.example.mydsl.parent'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.google.guava:guava:[10.0.1,14.0.1].
     Required by:
         project : > org.xtext:xtext-gradle-plugin:3.0.2 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.9.0
         project : > org.xtext:xtext-gradle-plugin:3.0.2 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.9.0
      > Failed to list versions for com.google.guava:guava.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/com/google/guava/guava/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by oehme** [comment]
If there's an outage, it doesn't matter what version we're asking for.

JCenter is built into the plugin portal. Gradle could switch to Maven Central, but that doesn't contain everything that JCenter contains, so would probably lead to some people's builds starting to break. Basically, they don't have a great option.

You can set up your own Nexus and mirror the plugin portal if you think that would be more available than JCenter.

**Comment by cdietrich** [comment]
the question then is: would there be a "no jcenter redirects" flag to test out of your plugin dependencies are on maven central and gradle plugin portal directly or if we depend on stuff that is on jcenter only

**Comment by cdietrich** [comment]
e.g. https://repo1.maven.org/maven2/com/google/guava/guava/maven-metadata.xml is there but it seems to be ignored or the jcenter one is additionally queries due to the range

**Comment by oehme** [comment]
There is no such flag. I'm sure the Gradle team would ensure all transitive deps are either in the portal or in Central if they ever make the switch away from jCenter.
