### ISSUE TITLE
How to configure this plugin to generate java sources from Xcore

### ISSUE THREAD

**Issue by ghillairet** [xtext/xtext-gradle-plugin#25]
I've been trying to use this plugin to generate java sources from an Xcore file. You can find the build file 
[here](https://github.com/ghillairet/xcore-gradle-example/blob/master/build.gradle).

Although it generates the classes (and java source) from the xcore model into the /build folder, I cannot reference these from other java classes from within the project. Would it be doable to copy the generated java files into the current source folder?

My second issue is that the xcore generator does not seem to work when I'm referencing ecore types. Remove the comment [here](https://github.com/ghillairet/xcore-gradle-example/blob/master/src/main/resources/model.xcore#L4) and the following error will happen:
```
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/Users/guillaume/Experimental/xcore-gradle-example/src/main/resources/model.xcore line : 4)
```

Last issue is that modifying the `DEFAULT_OUTPUT.dir` value in the build file does not seem to have any effect.

**Comment by oehme** [comment]
The generated files are not visible from Java because you didn't announce that the default output generates Java code. Also, why is there a SIDEKICKS output? That was just a part of the example project and makes no sense for XCore. Here's what I would configure:

```
output {
  dir = 'build/xcore/main'
  producesJavaFor sourceSets.main
}
```

Unfortunately XCore's generator does not care about the output.dir property. You'll have to adjust that in the GenModel annotation in your xcore files, too. You could open a bug for XCore and ask them to use the standard OutputConfiguration API.

If you want to reference Classifiers from .ecore files, you will also need to register the EcoreSetup:

```
languages {
    ecore {
      setup = 'org.eclipse.xtext.ecore.EcoreSupport'
    }    
}
```

**Comment by oehme** [comment]
I'll close this since there is nothing to fix on the plugin's side. But feel free to ask more questions =)

**Comment by ghillairet** [comment]
Thanks,

I didn't understand what the SIDEKICKS thing was for, that's why I kept it.

Still I can't manage to have it work, the generator complains that it can't find `GenModel` class, so I guess I am missing some dependencies to make it work. Here the list of dependencies I have

```groovy
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'

    xtextTooling 'org.eclipse.text:org.eclipse.text:3.5.101'
    xtextTooling 'org.eclipse.core:org.eclipse.core.resources:3.7.100'
    xtextTooling 'org.eclipse.xtext:org.eclipse.xtext.ecore:2.9.0.beta5'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.1.100'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen.ecore.xtext:1.2.0'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.3.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.common:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen:2.10.0-v20150123-0452'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen.ecore:2.10.1'
}
```

The errors I get

```
22:19:52: Executing external task 'build'...
ERROR:GenModel cannot be resolved. (file:/Users/guillaume/Experimental/xcore-gradle-example/src/main/resources/model.xcore line : 1)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/Users/guillaume/Experimental/xcore-gradle-example/src/main/resources/model.xcore line : 9)
:xtextGenerate FAILED
```

Should I include all dependencies from a ecore.codegen plugin?

I have also been trying to use the maven xtext-maven-plugin to achieve the same thing, but I get the same result. All examples I found are using tycho and not standard maven to do that, like this [project](https://github.com/sculptor/sculptor/blob/007c4b76dda74ce96b53d8b3b3c34674c5019046/sculptor-generator/sculptor-metamodel/pom.xml#L28). 

So that would confirm the fact that some dependencies are missing and those are added by tycho, or am I missing something? Has anyone generated xcore code from maven/gradle without tycho?

**Comment by oehme** [comment]
You are missing `org.eclipse.emf.ecore.xcore.lib` on your `compile` classpath. Your model files link against that library.

**Comment by ghillairet** [comment]
Thanks, it's working fine now.

Here the final build file

```groovy
plugins {
    id "org.xtext.xtext" version "0.3.25"
}

group 'io.github.ghillairet'
version '0.1.0-SNAPSHOT'

apply plugin: 'base'
apply plugin: 'java'

sourceCompatibility = 1.8

xtext {
    version = '2.9.0.beta5'
    encoding = 'UTF-8'

    sources {
        srcDir 'src/main/resources'
    }

    languages {
        ecore {
            setup = 'org.eclipse.xtext.ecore.EcoreSupport'
        }
        codegen {
            setup = 'org.eclipse.emf.codegen.ecore.xtext.GenModelSupport'
        }
        xcore {
            setup = 'org.eclipse.emf.ecore.xcore.XcoreStandaloneSetup'
            consumesJava = true
            output {
                dir = 'src/main/java-gen'
                producesJavaFor sourceSets.main
            }
        }
    }
}

clean {
    delete 'src/main/java-gen'
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'

    compile 'org.eclipse.emf:org.eclipse.emf.common:2.10.1'
    compile 'org.eclipse.emf:org.eclipse.emf.ecore:2.10.1'
    compile 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.1.100'

    xtextTooling 'org.eclipse.text:org.eclipse.text:3.5.101'
    xtextTooling 'org.eclipse.core:org.eclipse.core.resources:3.7.100'
    xtextTooling 'org.eclipse.xtext:org.eclipse.xtext.ecore:2.9.0.beta5'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen.ecore.xtext:1.2.0'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.common:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.10.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.3.1'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.1.100'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen:2.10.0-v20150123-0452'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.codegen.ecore:2.10.1'
}
```

**Comment by oehme** [comment]
Can you please file a bug against Xcore to straighten out their transitive dependencies?

Once that is fixed, it should look like this:

```
dependencies {
    compile 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.1.100'
    testCompile group: 'junit', name: 'junit', version: '4.11'
    xtextTooling 'org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.3.1'
}
```


Apart from that, you can write 

```
plugins {
    id "org.xtext.xtext" version "0.3.25"
    id 'java'
}
```

and remove these two lines:

```
apply plugin: 'base'
apply plugin: 'java'
```

That makes it a little more consistent.

**Comment by ghillairet** [comment]
Here the link to the xcore [bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480302)
