### ISSUE TITLE
Outlet configurations

### ISSUE THREAD

**Issue by pellepelster** [xtext/xtext-gradle-plugin#40]
I have a language using a custom _OutputConfigurationProvider _ that was previously generated by the < 1.x version auf the xtext-gradle-plugin.
I'm in the transition process to 1.x and have problems understanding the relation between the sourceset and outlets that are assumend by the plugin.
The documentation states 

> If you apply the Java plugin, an Xtext Generator task is created for every Java SourceSet

I assumed that I needed to create a sourceset for every outlet that is defined in my _OutputConfigurationProvider _ but the build fails due to missing outlet. 
When I manually create the outlet everything works.

Do I need to create the outlets manually or is there some magic that is missing?
What is the generateXXX Task ment for that is created for each sourceset?

**Comment by oehme** [comment]
A `SourceSet` groups code that should be compiled together, e.g. a production (main) SourceSet and a test SourceSet. All source files found in the folders of one SourceSet are indexed/validated/compiled together by the corresponding `generateXXX` task.

An Outlet defines that your generator wants to split the generated code into different categories (e.g. Html outlet and Java outlet). You have to define your language's outlets as shown in the `Configuration Options Overview` in the documentation. That chapter also describes how you could adjust the output folders for every combination of SourceSet and Outlet.
