### ISSUE TITLE
org.xtext.builder ignores changes in xtextLanguage JAR in mavenLocal() when running under Gradle daemon

### ISSUE THREAD

**Issue by vorburger** [xtext/xtext-gradle-plugin#41]
Hi @oehme - how is it going at Gradle? ;-) Thanks a lot for continuing to maintain xtext-gradle-plugin.

Unless I'm stupid, I think there is a bug in org.xtext.builder causing it to ignore changes in xtextLanguage JARs in mavenLocal() when running under Gradle daemon - were you aware of this? I've no idea of course if this is something bad in the xtext Gradle plugin (like does it perhaps 'forget' to "release" some.. "handle" to the xtextLanguages dependencies), or an indication of a more fundamental problem in the implementation of the Gradle daemon cache.

Here's how you should be able to reproduce this problem:

    echo "org.gradle.daemon=true" >>~/.gradle/gradle.properties
    git clone https://github.com/xtext/maven-xtext-example
    cd maven-xtext-example/my.mavenized.herolanguage.releng
    mvn install
    cd ../example-project-gradle
    ./gradlew test
    cd ../my.mavenized.herolanguage
    nano src/my/mavenized/jvmmodel/HeroLanguageJvmModelInferrer.xtend 
    mvn install
    cd ../example-project-gradle
    ./gradlew test
    cat build/herolang/main/my/company/Superman.java

See what I'm trying to show - making some change to the HeroLanguageJvmModelInferrer.xtend which breaks it, say I changed `toMethod("hello"` to `toMethod("helloXX"`, but whatever - and the next generation should fail because there is a test for the method name, or even just look at the gen. code, but .. nope! It but doesn't - because example-project-gradle is still using the original `herolanguage` version from before the change, when running under the Gradle daemon!! Uh uh. :-( Now if you remove the `org.gradle.daemon=true` from the `~/.gradle/gradle.properties` and `./gradlew test` again, or use `./gradlew --stop` first, then it will magically fail (resp. gen. diff. new code..), because now (only) the change made to the DSL/Generator is taken into account.

Note that launching it using `./gradlew --no-daemon test` does not seem to help, or not always. Using use `./gradlew --stop` sometimes. Removing remove the `org.gradle.daemon=true` from the `~/.gradle/gradle.properties` always does the trick and makes it forget however this is cached wherever. I understand these 3 options should all lead to the same, but I've observed they don't reliably - go figure.

PS: I was originally using mvn 3.3.9 (probably not important), and Gradle 2.9 through the wrapper of the maven-xtext-example/example-project-gradle as seen in https://github.com/xtext/maven-xtext-example/blob/master/example-project-gradle/gradle/wrapper/gradle-wrapper.properties#L6, and org.xtext.builder" version "1.0.0-RC1" as in https://github.com/xtext/maven-xtext-example/blob/master/example-project-gradle/build.gradle#L5. FTR: I'm proposing upgrading both to latest via https://github.com/xtext/maven-xtext-example/pull/37, and have retested the scenario outlined above with both, but that does not help... :-(

PPS: Chapter "6.3.7. What can go wrong with Daemon?" on https://docs.gradle.org/current/userguide/gradle_daemon.html sounds interesting and relevant in this context - in particular "... and third party plugins can destabilize the Daemon process through defects such as memory leaks or global state corruption."

**Comment by oehme** [comment]
Thanks for pointing me at this, Michael. There is no deeper issue with the daemon. It's just me being too dumb to listen for changes in the content of the jars ;) The fix will be out as 1.0.3 shortly.

It's going great at Gradle, I'm having lots of fun and feel super productive. Being able to travel while I work is a great bonus. It feels like the right place for me :)
