### ISSUE TITLE
Exclude security xtext/xtendlib jar artefacts by default, due to possible DuplicateFileException

### ISSUE THREAD

**Issue by Buggaboo** [xtext/xtext-gradle-plugin#43]
The fix right now for the DuplicateFileException is this, this happens when dexing the class files:

```gradle
android {
  packagingOptions {
    // from xtendlib >=2.9.2
    exclude 'META-INF/ECLIPSE_.RSA'
    exclude 'META-INF/ECLIPSE_.SF'
  }
}
```

**Comment by oehme** [comment]
@dhuebner I think our artifacts on Maven Central shouldn't even contain these Eclipse signatures. Is that correct?

**Comment by dhuebner** [comment]
@oehme It depends on the version. At the moment  2.11.0-SNAPSHOT do not have them, because we can't use eclipse signing.

**Comment by oehme** [comment]
And I think we generally shouldn't sign them on Maven Central. We can sign them when we upload them to the Eclipse repositories. Does that sound right to you?

**Comment by cdietrich** [comment]
is that a problem when maven and tycho dependencies are mixed?

**Comment by dhuebner** [comment]
@cdietrich Yes

**Comment by oehme** [comment]
Should they ever be?

**Comment by dhuebner** [comment]
@oehme The android dup-file problem comes up from time to time and there is a workaround for that. The Java SecurityException issue comes up very often and there is no workaround for that.  I would rather suggest to create a extra runtime libs (xtext,xbase) artifacts for android, like we did it for GWT

**Comment by oehme** [comment]
Creating extra runtime libs is more hassle for the user and for us than the
simple workaround above. So if we really need to sign the jars on Maven
Central (which feels weird as we want to get away from "eclipsiness"), then
let's just close this as wontfix.

2016-08-04 9:29 GMT+02:00 Dennis Huebner <notifications@github.com>:

**Comment by oehme** [comment]
Fixed on master, will be included in the next bugfix release.
