### ISSUE TITLE
[gradle-xtend-plugin] compileJava fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kuniss** [xtext/xtext-gradle-plugin#45]
... Looks like an issue to me - see Google Groups thread https://groups.google.com/forum/#!topic/xtend-lang/5U5JQM1EVks.
Denis

**Comment by oehme** [comment]
Can you please share a small reproducible example? It looks like the encoding specified in your build does not match the encoding of your files.

The org.xtext.xtend plugin will use the same encoding as the corresponding JavaCompile task.

**Comment by kuniss** [comment]
I will try.
However, all files are encoded by CP1252.

The encoding specification for the Xtend compilation
```
tasks.withType(org.gradle.api.tasks.compile.JavaCompile) {
        options.encoding = "Cp1252"
}
```
is right, isn't it?

**Comment by oehme** [comment]
Yep, you can skip the package declaration BTW, the JavaCompile task is imported by default.

**Comment by kuniss** [comment]
I could strip it down the issue to a small project: [gradle-xtend-plugin-issue45-1.zip](https://github.com/xtext/xtext-gradle-plugin/files/173868/gradle-xtend-plugin-issue45-1.zip).

However, I guess, **it is not a Xtend plugin issue!** I use the Xtend plugin together with JNAerator which has an unversioned dependency to `org.eclipse.jdt.core.compiler` in the [POM](https://bintray.com/artifact/download/bintray/jcenter/com/nativelibs4java/jnaerator/0.12/jnaerator-0.12.pom)
```
		<dependency>
			<groupId>org.eclipse.jdt.core.compiler</groupId>
			<artifactId>ecj</artifactId>
		</dependency>
```
Which is resolved in the buildscript header. So, it is the first entry for `jdt` in classpath, I guess. It uses a different version of the jdt compiler than Xtend/Xtext plugin needs. This causes the problem, I guess.

Never would have expected such an interference...

Sorry for raising this issue. You may close it.

**Comment by oehme** [comment]
Thanks for verifying that it's not an Xtext issue. If you use the new plugin DSL

```
plugins {
 id 'org.xtext.xtend' version '1.0.3'
...
}
```

instead of the buildscript block, your plugins should be isolated.

**Comment by kuniss** [comment]
Excluding the `org.eclipse.jdt.core.compiler' dependencies solved the problem on my side:
```
buildscript {
                ...
		classpath ("com.nativelibs4java:jnaerator:0.12") {
			exclude group: 'org.eclipse.jdt.core.compiler'
		}
}
```

**Comment by kuniss** [comment]
@oehme I know, but the JNAerator Gradle plugin is not provided compatible to the new Gradle plugin DSL. :-(

**Comment by oehme** [comment]
I see, you should definitely open an issue for them :)

**Comment by vorburger** [comment]
Just FTR because I've found this while googling "gradle xtend encoding" when hitting ERROR:no viable alternative at input 'Â' for a « character: The following in build.gradle also sets the encoding for Xtend to UTF-8:

    compileJava.options.encoding = 'UTF-8'
