### ISSUE TITLE
Incompatibility with gradle 2.12

### ISSUE THREAD

**Issue by maul-esel** [xtext/xtext-gradle-plugin#49]
I'm having problems using the plugin with gradle 2.12. The build fails with the following error:

>An exception occurred applying plugin request [id: 'org.xtext.xtext', version: '1.0.0-RC4']
> Failed to apply plugin [id 'org.xtext.xtext']
> Could not create an instance of type org.xtext.gradle.tasks.XtextExtension_Decorated.

A look at the stacktrace reveals the following root cause:

> [...]
> Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.DefaultSourceDirectorySet.\<init\>(Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;)V
	at org.xtext.gradle.tasks.XtextExtension.\<init\>(XtextExtension.java:41)
	at org.xtext.gradle.tasks.XtextExtension_Decorated.\<init\>(Unknown Source)
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
	... 59 more

It seems the constructor of the `DefaultSourceSet` class has changed (multiple times) since the 2.11 release ([see here](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/groovy/org/gradle/api/internal/tasks/DefaultSourceSet.java#L43)).

This might already be fixed in `master`, since apparently `XtextSourceDirectorySet` is used instead of `DefaultSourceSet`, so maybe another release is all that is needed?

**Comment by oehme** [comment]
Please upgrade to the current version of the plugin, which is 1.0.4

**Comment by maul-esel** [comment]
Thanks. I'm sorry, I was looking at https://plugins.gradle.org/plugin/org.xtext.xtext which listed 1.0.0-RC4 as latest (probably because the plugin was renamed?)

**Comment by oehme** [comment]
Thanks, I'll see if I can put up a deprecation notice :)
Am 05.04.2016 20:29 schrieb "maul.esel" <notifications@github.com>:
