### ISSUE TITLE
clean task not clearing down generated folders

### ISSUE THREAD

**Issue by fluxtah** [xtext/xtext-gradle-plugin#5]
Hi,

Is there a way to configure the plugin to clear the DEFAULT_OUTPUT output folders when running a clean? It seems that when I run a gradle clean with a standard xtext-gradle-plugin project it does not clean previous generated source files or is there something I am missing?

**Comment by oehme** [comment]
Indeed, the cleanXtextGenerate task is not included in the clean task. As a workaround, add this to your build:

`clean.dependsOn(cleanXtextGenerate)`

**Comment by fluxtah** [comment]
Cheers!

**Comment by oehme** [comment]
This is fixed in 1.0.0
