### ISSUE TITLE
"ERROR:Abstract methods do not specify a body" thrown for Java 1.8

### ISSUE THREAD

**Issue by lkolek** [xtext/xtext-gradle-plugin#52]
"ERROR:Abstract methods do not specify a body" thrown by org.xtext.xtend plugin when compiling interface like below:

<code>
interface X{
	def boolean foo()       {false }
}
</code>

Seems that corresponding .java files are generated, but that error prevents further tasks.

**Comment by oehme** [comment]
Xtend does not support default methods yet, so this error is expected. Feel free to create a feature request on [Bugzilla](https://bugs.eclipse.org/bugs/buglist.cgi?component=Core&product=Xtend&resolution=---)

**Comment by lkolek** [comment]
It works great in plugin eclipse, so xtend 2.9.1 DOES support it.
It also seams that gradle xtend plugin DOES generate proper java files - but I must admit, that I'm not totally sure what comes from eclipse and what from gradle plugin.
If above statement is correct, the only problem is error that is thrown.
BTW. Workaround is to generate java from xtend in eclipse and just compile java classes using gradle.

**Comment by oehme** [comment]
I had completely forgotten that this was implemented :) Thanks for correcting me!

I just checked and indeed the plugin does not pass on the Java source level correctly by default.

**Comment by lkolek** [comment]
xtend {
	generator{
		javaSourceLevel = 1.8
	}
}

did the trick.

**Comment by oehme** [comment]
Yes, the explicit version as you just showed was covered by the tests, but it should be automatically be configured based on the value from the `java` plugin.

**Comment by oehme** [comment]
Fixed by #bce0bd2fd98015be7ef4ab101cafd287c0273fb5. Thanks again for spotting this! Bugfix release will be out in a few minutes.

**Comment by lkolek** [comment]
Thank you for very fast reaction.

**Comment by sirolf2009** [comment]
```
			<plugin>
				<groupId>org.eclipse.xtend</groupId>
				<artifactId>xtend-maven-plugin</artifactId>
				<version>2.9.1</version>
				<configuration>
					<javaSourceVersion>1.8</javaSourceVersion>
				</configuration>
			</plugin>
```
Maven version of the gradle fix above, in case anyone is interested
