### ISSUE TITLE
Plugins broken on Android Studio >=2.11

### ISSUE THREAD

**Issue by Buggaboo** [xtext/xtext-gradle-plugin#53]
Hi,

I'm reporting that the xtext-idea-plugin is broken on android studio >= 2.11.

Is there a version restriction, built-in?

**Comment by oehme** [comment]
Could you please attach a stacktrace?

**Comment by Buggaboo** [comment]
Sorry, I made a noobish mistake. I didn't manage to get a stacktrace.

I uninstalled the plugins, then I tried adding it again.
But when I tried adding them, the plugins wouldn't appear on the list of installable plugins for the same remote repository.

**Comment by Buggaboo** [comment]
Weird. I reinstalled with the stable (non-snapshot) version now the problem is gone.
