### ISSUE TITLE
xcore: How to resolve imports

### ISSUE THREAD

**Issue by palador** [xtext/xtext-gradle-plugin#63]
I'm currently try to integrate your wonderful plugin into my build and it works as expected... as long I have just one xcore file. With two of them, one referencing classes of the other, there are problems:

``
ERROR:PipeType cannot be resolved. (file:/home/palador/dev/pipeman/src/models/src/main/xtext/document.xcore line : 12 column : 12)
ERROR:de.sc.pipeman.model.material cannot be resolved. (file:/home/palador/dev/pipeman/src/models/src/main/xtext/document.xcore line : 8 column : 8)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/home/palador/dev/pipeman/src/models/src/main/xtext/document.xcore line : 12 column : null)
``

I tried to fix it myself, but I'm not that much into codegeneration configurations. Here are some snipets of my sources:

build.gradle
``
...

apply plugin: 'org.xtext.builder'
apply plugin: 'org.xtext.xtend'
apply plugin: 'java'
apply plugin: 'base'

xtext {
    version = "$xtext_version"

    sourceSets {
        main {
            srcDir 'src/main/xtext'
        }
    }

    languages {
        ecore {
            setup = 'org.eclipse.xtext.ecore.EcoreSupport'
        }
        codegen {
            setup = 'org.eclipse.emf.codegen.ecore.xtext.GenModelSupport'
        }
        xcore {
            setup = 'org.eclipse.emf.ecore.xcore.XcoreStandaloneSetup'
            generator.outlet.producesJava = true
            generator.javaSourceLevel = '1.8'
        }
    }
}

sourceSets {
    main {
        output.dir("$buildDir/xcore/main", buildBy: "generateXtext")
    }
}

...
``

document.xcore:
``
@GenModel(
    modelDirectory="./build/xcore",
    complianceLevel="8.0"
)

package de.sc.pipeman.model.document

import de.sc.pipeman.model.material

class PipemanDocument {
    String title
    refers PipeType defaultPipeType
}
``

material.xcore:
``
@GenModel(
    modelDirectory="./build/xcore",
    complianceLevel="8.0"
)

package de.sc.pipeman.model.material

class PipeType {
    String name
}
``

**Comment by oehme** [comment]
Could you create a reproducible project on GitHub please? That would make it much easier to diagnose what might be wrong here.

**Comment by palador** [comment]
Ok, no problem: https://github.com/palador/xcore-example

**Comment by oehme** [comment]
This import statement is incomplete:

```
import org.palador.xcoreexample.material
```

It should be

```
import org.palador.xcoreexample.material.PipeType
```

I wonder how that worked in the IDE?

**Comment by palador** [comment]
Ohh, you're right! Thank you so much!

btw, I'm using intellij idea, and there is no xtext support, but this xcore dsl is quite simple so I don't need it... just this one typo costed me half a day :( .

**Comment by oehme** [comment]
There is an Xtext plugin for IntelliJ. But I'm pretty sure no XCore plugin
atm.

Am 25.08.2016 9:25 Nachm. schrieb "palador" <notifications@github.com>:

**Comment by oehme** [comment]
By the way your build is way, way faster if you remove the unnecessary repositories:

```
mavenCentral()
maven {
  url 'http://maven-eclipse.github.io/maven'
}
```

And these dependencies which don't even exist:

```
xtextLanguages "org.eclipse.emf:org.eclipse.emf.common:$emf_version"
xtextLanguages "org.eclipse.emf:org.eclipse.emf.ecore:$emf_version"
xtextLanguages "org.eclipse.emf:org.eclipse.emf.ecore.xmi:$emf_version"
```

Otherwise Gradle will search for them in every repo.
