### ISSUE TITLE
No Warning/Error is User configures Source Folder as Output folder

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#64]
The plugin excludes output folders from beeing a model folder.
thus the xtend plugin wont find anything if the xtext plugin generates to src/main/java

https://github.com/cdietrich/gradle-xtext-xtend-problem

**Comment by oehme** [comment]
I assume this is about the "generate once" use case where a language generates some stubs that the user has to fill out. This now works as expected. If you set `outlet.cleanAutomatically=false`, then the folder will not be ignored and none of the output files will be overwritten on subsequent builds.
