### ISSUE TITLE
Avoiding "The type ... is already defined" errors

### ISSUE THREAD

**Issue by szarnyasg** [xtext/xtext-gradle-plugin#72]
I keep getting "Type type ... is already defined" errors in Eclipse. The [Xtend Compiler](http://xtext.github.io/xtext-gradle-plugin/xtend.html) page states that:
> Hooks into 'gradle eclipse', so the Xtend compiler is configured for your project when you import it into Eclipse

However, this does not work for me. I created a simple project that reproduces the issue: https://github.com/szarnyasg. If I execute the `eclipse` task manually with `./gradlew build eclipse` (as shown in [this isse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462172#c1)), the problem goes away. Another workaround is do delete the build directory (either from Eclipse or from another application), which also fixes the issue.

Is there a way to avoid these errors without explicitly invoking the `eclipse` task?

I use the latest Gradle (3.2.1) and the latest version of the Xtext Gradle plug-in (1.0.15).

**Comment by oehme** [comment]
The problem is that the Xtend Gradle plugin has no way of configuring the Xtend compiler settings in eclipse, it's a missing API in Gradle. The Gradle plugin uses a different default than the Eclipse plugin, which is why you get those duplicate type errors. 

The only way to fix that is an api in Gradle that allows us to model preferences. If you are interested in contributing that let me know.

**Comment by szarnyasg** [comment]
@oehme thanks for the quick reply - I am not that proficient in Gradle internals, so running the `eclipse` task is a perfectly acceptable workaround for me.

However, I think this should be clarified in the docs. I'd be happy to open a PR updating the [Xtend Compiler](http://xtext.github.io/xtext-gradle-plugin/xtend.html) page.

**Comment by oehme** [comment]
Adding a "Limitations" section would indeed be welcome :)

**Comment by DanySK** [comment]
I was experiencing a similar problem. In my case, the root issue was the `build/xtend/main' folder being included in the Eclipse classpath. I worked it around as follows:

```gradle
eclipse.classpath.file {
    whenMerged { classpath ->
        classpath.entries = classpath.entries.findAll { entry -> 
            !entry.path.contains('build/')
        }
    }
}
```
