### ISSUE TITLE
Question : Outlet without cleaning strategy

### ISSUE THREAD

**Issue by didos36** [xtext/xtext-gradle-plugin#78]
Hello,

I have a Xtext Language that define several output configuration, but with some different strategy regarding delete existing files. One delete existing file, the other only create file is not exiting.

I tried someting like 
` outlets {
                    DEFAULT_OUTPUT {
                        producesJava = true
                    }
                    DEFAULT_OUTPUT_ONCE {
                        producesJava = true
                        cleanAutomatically = false
                    }
}`

but this is working.
Any idea?

**Comment by oehme** [comment]
What is not working? Can you please provide a reproducible example project on GitHub?

**Comment by peterssas** [comment]
I have the same problem, are there any solutions for the problem?

**Comment by peterssas** [comment]
I have the same problem, are there any solution for this?
A small example: https://github.com/peterssas/xtext-gradle-problem.git
The File "TestEntityGenOnce" is modified and will be overwrite during next gradle build

**Comment by oehme** [comment]
Thanks for the example! I had wrongly assumed that Xtext merges the output configuration, but that's not the case. So the the Gradle plugin needs to do it instead.

**Comment by didos36** [comment]
Hello,

Do you plan a bug fix?

**Comment by oehme** [comment]
Not at the moment but pull requests are welcome
