### ISSUE TITLE
Minimum gradle version is not specified

### ISSUE THREAD

**Issue by Dunemaster** [xtext/xtext-gradle-plugin#86]
Please, specify minimum gradle version which can be used with this plugin

**Comment by cdietrich** [comment]
@ArneDeutsch is this fixed now?

**Comment by ArneDeutsch** [comment]
With the upcoming plugin version the minimum will be raised to 4.3. Not sure yet where to document this.

**Comment by cdietrich** [comment]
i think the documentation resides here https://github.com/xtext/xtext-gradle-plugin/blob/gh-pages/xtext-builder.md

**Comment by cdietrich** [comment]
@oehme what is the std. way to specify a minimal gradle version?

**Comment by oehme** [comment]
Added the supported versions to the website.
