### ISSUE TITLE
generateXtext don't find model sources if they placed in java-folder

### ISSUE THREAD

**Issue by peterssas** [xtext/xtext-gradle-plugin#87]
My Model-Files are placed in the java folder.
How I have to configure the xtext-task to find them?

I tried  the following, but the task always ends with generateXtext NO-SOURCE

`
xtext {

    version = '2.10.0'
    languages {
    	myDsl {
      	    fileExtension = 'myDsl'
        	setup = 'test.myDsl.MyDslStandaloneSetup'
        	generator {
				javaSourceLevel = '1.8'
    			outlets {
    				DEFAULT_OUTPUT {
    					producesJava = true
    				}
		    		FORM_GEN_OUTPUT {	
		    			producesJava = true
		    		}
		    		TEST_GEN_OUTPUT {
		    		}
		    		TEST_OUTPUT {
		    		}
    			}
			}	
      	}
     }
     sourceSets {
        main {
        	srcDir 'src/main/java'
        	output {
        		dir (xtext.languages.myDsl.generator.outlets.DEFAULT_OUTPUT, 'src/main/java')
        		dir (xtext.languages.myDsl.generator.outlets.FORM_GEN_OUTPUT, 'src/main/java-form-gen')
        		dir (xtext.languages.myDsl.generator.outlets.TEST_GEN_OUTPUT, 'src/itest/java-gen')
        		dir (xtext.languages.myDsl.generator.outlets.TEST_OUTPUT, 'src/itest/java')
        	}
        }
    }
}
`

**Comment by oehme** [comment]
Can you please provide a small, reproducible example on GitHub? Otherwise it's hard to tell what might be the problem.

**Comment by peterssas** [comment]
I created a small example on https://github.com/peterssas/xtext-gradle-problem.git
I used the domainmodel-example from xtext.

The reason for the issue is if the DEFAULT_OUTPUT is equals to "src/main/java".
In my project I used it to generate some classes once a time.

**Comment by oehme** [comment]
The input and output folder can't be the same. That would break any kind of incremental build. You need to generate your sources into a different folder, e.g. `src/gen/java`.

We should forbid this kind of misconfiguration to avoid any confusion like this.

**Comment by peterssas** [comment]
Is this only in the plugin or shuldn't I do this in eclipse as well?
I ask, because sometimes I have a workspace build issue in eclipse, then it look like an endless build. Eclipse build then "Update resource descriptions"

**Comment by oehme** [comment]
It's just a bad practice in general, even if it works in Eclipse.

**Comment by peterssas** [comment]
Thank you very much, 
this helps me a lot. I think no we can closed this issue.
