### ISSUE TITLE
 http://download.itemis.com/updates/ is down

### ISSUE THREAD

**Issue by hristo-vrigazov** [xtext/xtext-gradle-plugin#95]
While discussing GH-94, it was found out that  http://download.itemis.com/updates/ is down and was last up on 9 August 2017 00:11:14 GMT.

**Comment by cdietrich** [comment]
i already informed our admin team

**Comment by cdietrich** [comment]
@meysholdt do you have set up a mirror already? if so we should change the tool that it trys the mirror is the itemis server is down

**Comment by hristo-vrigazov** [comment]
Oh, sorry, I read your message as "open a ticket". Should I keep this one to keep people updated here as well?

**Comment by cdietrich** [comment]
its the wrong place anywhere. so you can close it

**Comment by cdietrich** [comment]
http://download.itemis.com/updates/ is back up
