### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by FunnyDevs** [xtext/xtext-gradle-plugin#97]
Hi! I 'm trying xtend and xtendroid samples but i am not able to use autocomplete on overriding fuctions inside class. When i click with mouse on the suggestion the IDE deletes the First lettera i errore instead of generate the fuctions. IS IT normal? Thanks

This is the problem

https://streamable.com/g0yg8

**Comment by oehme** [comment]
This is just the Gradle plugin, please open an issue for [Xtend](https://github.com/eclipse/xtext-xtend).

**Comment by FunnyDevs** [comment]
This is the error

> Error during auto build.: java.io.IOException: Invalid file name: ':'
> java.lang.RuntimeException: java.io.IOException: Invalid file name: ':'
> 	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:177)

**Comment by cdietrich** [comment]
See my other issues
