### ISSUE TITLE
xtext-gradle behaves inconsistently across architectures

### ISSUE THREAD

**Issue by alexandrebouchard** [xtext/xtext-gradle-plugin#98]
I am checking out a clean copy of a project built via xtext-gradle, running "./gradlew build" on two different architectures and getting an error on the generateXtext task on one architecture (an AWS instance with Ubuntu) and no error on another architecture (Mac OS). Both architectures use Java HotSpot(TM) 64-Bit Server VM 1.8.0, and the gradle wrapper script is based on the latest release version of gradle (4.2.1) and of xtext-gradle-plugin (1.0.19). The error itself (included below) is a bit hard to diagnose but may be related to circular dependencies across generated xtext files. 

One hypothesis I have is that since File.list() does not guarantee a consistent order, it may be the root cause of variability across platforms. But more fundamentally it would seem desirable that xtext-gradle-built shields the developer from the order in which the DSL files are processed (to avoid e.g. that refactoring a file name cause compilation to break). 

I provide more details below. Thanks in advance for any pointers.

Details
-------

Basic "reproducibility" instruction (putting quotes here as the error only arises on certain architectures, e.g. Ubuntu 14.04.5 LTS running in an EC2 t2.medium instance; not on Mac OS X or travis)  

```
git clone https://github.com/UBC-Stat-ML/blangSDK.git
cd blangSDK
git checkout f4735dbd00755d1e651953f0b8f0bd3405c0bb1d
./gradlew build
```

The errors encountered take the form

```
ERROR:The method or field Normal is undefined (file:/home/ubuntu/.blang/temp/blangSDK/src/main/java/blang/validation/internals/fixtures/Multimodal.bl line : 6 column : 35)
```

They are essentially some (but not all) of the instances where an XExpression invokes a method on an another type generated by Xtext. However I should note that I have other commits where the error is different but again comes up on one architecture but not the other. I should also note that in no case I have observed that compilation on these problematic cases break within eclipse.

For completeness, stack trace below

```
Caused by: org.gradle.api.GradleException: Xtext validation failed, see build log for details.
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:210)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:149)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by oehme** [comment]
It looks like you are using an old Xtext version (2.10). Please try upgrading to the latest version, because many Java linking related problems in the standalone compiler have been fixed since then.

**Comment by alexandrebouchard** [comment]
Thanks for the quick response! I working on it now (trying to fixing a small glitch I am encountering when upgrading to 2.12.0 (org.eclipse.xtext.junit4:2.12.0 not found on the maven sites)).

**Comment by alexandrebouchard** [comment]
Unfortunately, upgrading xtext did not fix the issue. Any other suggestions? Thanks again!

**Comment by oehme** [comment]
Can you try 2.13? These kinds of problems are usually in the underlying standalone builder, which the Gradle plugin calls. Maybe @cdietrich has seen this issue before?

**Comment by cdietrich** [comment]
no have not. maybe something wired in the inferrer?

**Comment by alexandrebouchard** [comment]
Thanks for the suggestion @oehme, I tried 2.13.0.RC1. Unfortunately I saw the same error message.

Regarding the inferrer, I give a few details below of one characteristic that may potentially explain the problem but I think generally it follows standard xtext patterns. 

But there is no error when building with eclipse so I was wondering if you guys have seen other situations in the past where the xtext plug-in and the eclipse xtext builder behave differently? Perhaps that they could share common causes. 

Thank you for your time.

### A bit more information on the inferrer

The general form follows the usual

```
  def dispatch void infer(BlangModel model, IJvmDeclaredTypeAcceptor acceptor, boolean isPreIndexingPhase) {
    acceptor.accept(model.toClass(model.name)) [
      <actual work here>
    ]
  }
```

where the ``<actual work>`` generates just a single java file. There are also a few public static inner classes generated, so one question I had is whether these should be registered somehow in the pre-indexing phase? If so, I am not doing it at the moment and wonder if that could explain the weird behaviour.

**Comment by cdietrich** [comment]
You should generate all classes the way as shown above

**Comment by cdietrich** [comment]
Hmmm and what kind is the missing field?

**Comment by cdietrich** [comment]
And of course the behaviour is 100 % different cause the impl is 100 % different.
The question is what causes the issue in your case. So it would be interesting it it happens with 
A dsl you can completely share as well eg the domain model example

**Comment by alexandrebouchard** [comment]
Regarding the question on the nature of the missing field,

```
ERROR:The method or field Normal is undefined (file:/home/ubuntu/.blang/temp/blangSDK/src/main/java/blang/validation/internals/fixtures/Multimodal.bl line : 6 column : 35)
```

refers to the XExpression

```
Normal::distribution(0.0, 1.0)
```

where ``Normal`` is a public type generated by xtext, and ``distribution`` is a static method.

**Comment by cdietrich** [comment]
so Normal is a top level type?

**Comment by alexandrebouchard** [comment]
Yes

**Comment by cdietrich** [comment]
hmmm then order should no play any role since it always announces the available types in the preindexing phase first. thus it would be interesting how to reproduce this with a dsl that can actually be changed/seen

**Comment by alexandrebouchard** [comment]
Just to clarify, the whole stack is open source (DSL itself is at https://github.com/UBC-Stat-ML/blangDSL/). But I agree it's a bit big so I'll see if I can create a simple example.

**Comment by cdietrich** [comment]
there is this wired construct in your code:

``` 
if (model.package != null) {
      output.packageName = model.package
    }
```

imho its a bad idea to change names afterwards

**Comment by cdietrich** [comment]
there is other stuff happening but with that complicated dsl it is really hard to debug. @oehme  any idea on how to log from dsl to gradle?

**Comment by cdietrich** [comment]
@szarnekow do you have any idea?

**Comment by szarnekow** [comment]
It's certainly not possible to compute different names in the pre-indexing phase and the post-indexing phase. You need to use the very same for your inferred types.

**Comment by cdietrich** [comment]
hmmm i still dont know enhough about gradle to get any log output from xtext to gradle.
try to log the type provider what it does

**Comment by cdietrich** [comment]
@alexandrebouchard can you please test a fixed inferrer e.g

```
val name = if (model.package !== null) model.package+"."+model.name else model.name
    acceptor.accept(model.toClass(name)) [
```

**Comment by alexandrebouchard** [comment]
@cdietrich thanks for the insight, that solved the errors I had in the src/main source set. The remaining errors (all in src/test) seem more benign. In case I can bother you with it, basically DSL files in src/test referring to DSL files in src/main complain that "type <DSL generated type> cannot be resolved"; I assume it's a simple matter of modifying the classpath for the gradle task but not being a gradle expert any example doing that would be greatly appreciated. One way or the other, a big thank you again!

**Comment by alexandrebouchard** [comment]
Thanks again guys. The last point is a bit orthogonal to the first one raised so I'll close this issue. 

Best,
Alex
